--- 
- :source: http://gemcutter.org
  :name: paperclip
- :name: presentable
- :name: geokit
- :name: faster_csv
- :name: thinking-sphinx
- :source: http://gemcutter.org
  :name: rails-footnotes
- :version: 2.3.4
  :name: rails
